{% set version = "1.6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qtlrel
  version: {{ version|replace("-", "_") }}

source:
  fn: QTLRel_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/QTLRel_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/QTLRel/QTLRel_{{ version }}.tar.gz

  sha256: e5f0a855a89329d3c50b14917ab9f94dd1ed388ac547fa25a955e94373c62885

build:
  merge_build_host: True   # [win]
  skip: True  # [r_base == "3.5.1"]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('fortran') }}  # [not win]
  host:
    - r-base
    - r-gdata
    - r-lattice

  run:
    - r-base
    - r-gdata
    - r-lattice

test:
  commands:
    - $R -e "library('QTLRel')"  # [not win]
    - "\"%R%\" -e \"library('QTLRel')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=QTLRel
  license: GPL (>= 2)
  summary: This software provides tools for quantitative trait mapping in populations such as
    advanced intercross lines where relatedness among individuals should not be ignored.
    It can estimate background genetic variance components, impute missing genotypes,
    simulate genotypes, perform a genome scan for putative quantitative trait loci (QTL),
    and plot mapping results. It also has functions to calculate identity coefficients
    from pedigrees, especially suitable for pedigrees that consist of a large number
    of generations, or estimate identity coefficients from genotypic data in certain
    circumstances.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
