{% set version = "1.15" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qtlrel
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/QTLRel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/QTLRel/QTLRel_{{ version }}.tar.gz
  sha256: 15403d0b0850de06888afb39e5487c713ee042c04287b8466452e08f51610094

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-gdata
    - r-lattice
  run:
    - r-base
    - r-gdata
    - r-lattice

test:
  commands:
    - $R -e "library('QTLRel')"           # [not win]
    - "\"%R%\" -e \"library('QTLRel')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=QTLRel
  license: GPL-2.0-or-later
  summary: This software provides tools for quantitative trait mapping in populations such as advanced intercross lines where relatedness among individuals should not be ignored. It can estimate background genetic variance components, impute missing genotypes, simulate genotypes, perform a genome scan for putative quantitative
    trait loci (QTL), and plot mapping results. It also has functions to calculate identity coefficients from pedigrees, especially suitable for pedigrees that consist of a large number of generations, or estimate identity coefficients from genotypic data in certain circumstances.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
