travis:
  secure:
    BINSTAR_TOKEN: XOM+v3sa/WrQZVFrjjeTGC0Wdjf39m2hYugt8aob1XtUdjQ5oV76lQjFXhYoQljHGRsz2OeLoXS36iRd7g3tKO9Zsp1GkVMD8XF1HucJzKvvUt3rWIVxg6tjegHugZOJCbktNxigaQHwvExCa8G66vC88Zyyj65/gPEUK3Qr/IBiRA45NwYQzCi81U4Tg7jGTqlcL3RVBPbCi6MAV8R0+ufx1vTeY9axRgoAuzaAAxkK83QAWyGHHU2PHUpcuApGC3TgsQl4ZHVunwzYHv9Weugauqz0RD/60pkYYf/S9Q6z1QiFjITjZPgMhmhDKGwBl9zgngP1LHDswPJ2PTNAsc50MpgL9gw43dpI5SEzU8e/i9SFazqq/wcGQUfLSZ4g7V5PtFrE8FMyoMqI9hDxD331njS3D+unExpZb916GErsSWYetwXY1RQDRhR7bfsYcTQuUIDst6U83/o8SoeriDkZzeSloZ+VF3SVOtn66nKGD0Laum59mNcHzzfwPrbh+qsetlapUkOt837dv6MGU/dkGhurmXxei6PqLA23878E6ZHd0X8VLDUfQJ1zJHQHWRCFaIVEnTB9SRV17B2KPrbarF0j3Z+Py7Nk+J7ZAwl9COIqK77TfX855gtCM4YpnHAw7ujcAoEw9QI1DszELPF6g2arKfaNuAmRrosqHy4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
