travis:
  secure:
    BINSTAR_TOKEN: KFAmbEjmfiSWAHuE5jFZL+RCoXQr5k5/ORmWBBTMZW/cCOXXeeEraJt2I/amUtNMeMkEtq0tOg4GS35HaLS6l9Yq/k09BSQuo2GFlKG4oCmwDRZfXNnjBL3/xmhXd5phLBJekcGJFL3sKg+tmmYRi1EWs5Y/+mtkQ9vytaRIA5wAcvr5nrpz2Zj4VMumoZ+10aqjlUM37JZwH+uxuE+o0sljoGXyFyAtS8s7LZwDmK05jrVxgIJop0TIH4EgiQvsTQNgaYVFuwlpC2QAwkIllA7RXBwXMIaK5w+QwZH/lXDoqzMZQb7duQ9/rNaB7K15lt6/s29leo5prYImZHR7voqY5siskxxRjsnf6ypTESjKz3DjXnQHbHvkUJ3G+GfTKawE7ov1NKttsqnM0YuLGRySHnl3pjJ5u4VC6Uz6UGkfFKVDD2V/YDJo6tQ2ZXdm6hryn1dM1TI9/qvDiCok5GV27dJqfmewYf5i3JM1EbuhARec+zI8OGHGOitSmhNc5OKDqgyeTKmqWECj+sOYC6zYsSkpFhOOjZaoUWQD/2QvUkklhf9exqFAjHTV4cnqznCfPhMMbTlndlUJvVVZ/kCFWz8+AgblMT5tjm0Tyx/vxlnc57sp8g+gBtsL/dUPK5Bt1OPOUcuJduuWs1nxHybQ2FQJDKzsOURtlVgWCbc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
