travis:
  secure:
    BINSTAR_TOKEN: ZMroPe7lgfH4gT2h+oUbA5sk8d5ikA8BpEmF8k8yYlZiQsZ5bOzQsTHrlMk0kekeCY1W0sIrvGxVW/S8FV5ILoLPKh7Koa6+vA4MPVL+N8+KOp4Vcf0TiTWNHuNL+kAONhXgJisL9efNeaaOnCiU5rxlcwZHfcs+ZViM9/Wa988BMgod9vdExUyddukMJXBAQsq3r0P5hHWwiculCgv3O7go1fJN1OYwQyPqcMnJOw6MyvR5t35NPIi/AyKV4RbMs3oCZ5PAarRSXCs1UI3pUHK+oN07fUHvvJLdwbU10O3jbhJMar1Ut3SKbk/H9E0XGYYUk5Js8akNOxxtZpE3SfjukNq1W43UEKQYvY1zfhu7K+PoEKiDPOffdBXZtMnnA+jZo01AM74TjYwC2aC87IkXu/su1qGKnB/qoFGhEopTAYJzK2/0gsoY244aI6kEezi0w57uCABfINdN5ZKsMPfqdVIFsp0yTza1F8lApwYX1iHSDkfctnX2XHqTSHKiImmZiqY2MKjEMCJ0kC8YVfiTlLUgWXeLfGjx3OF4U6KrOERQVtuFKx9HfC5dCTu0sjiKFUfLsjnPARv5UEhNDSlF8KjpxdT8S3swTxSGZ+GFYA5uLlrLorLEBCWMUmE9sXyCA13pN4H69nfGmQe2YQylRInOsJXhd8HJiDvlhws=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
