travis:
  secure:
    BINSTAR_TOKEN: MeQzZAIKh/vqITMeAiYuap2XHhQTfnA0hf/y2Tc83SaL6v0/PPjfhcRU1BlipfBgz1O/LjK/vNd7+JZD6ri9qAW271n7zaQUcPd93yFL+tvOocmN/IgjbmfsAZlTeN5OSiIN/J/kGMaksquq3mQ04hKHxpIH6jyTdstJbaoaJHSCe5cfUOyCIaGTGOUb7iOWBP6FysBhrdNZJ7JKeJ4e7+HXjkbKQw27N3Bx1prEq0xUgPU/KIb27v6+Q0G8TMVrDzQQYhmx3SOmKXwW76HOaW7UNI7s8/fe40AxPzUTnzYgRLHPbwsEm9xCUshruh2wy2uAiqMPalIMizGc0pT25fc50okTtIzMT+VagSZDZTPsC74il46Ppe1znB322EWcKUvu82igJ2WMNesoYI2wgTE7dbU3iZ9Fc8JznrUFDvU9XkP7zq8+EjuOE4UbiiqdTVsPz+jWn2goMm4XrG3RcJF/CDrmNEQ9X4Husfobb9EtE4RABsyLVcb7Kh3pguRo+/24xz4QCvyHIEpvpMPaqEKyV3EXUHJkSY3o9cTOg82nryRKA1b8IwDKp2xQ079PKMjhUrDPcRDwKh+5TNRZAWD0Y/kwIsltSEocqDJKjyYWYPUMB82HKDJd1DrwEN+DkozQr5i8MGsUTSGZfABFulNW+A8Y5wfVsixQaXbTAXo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
